### ISSUE TITLE
create icon

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/OneShotPrototype#15]

**Comment by gojirra55** [comment]
Please post the required dimensions.

**Comment by omegabytes** [comment]
- Small Icon
-- 108 x 108 pixel PNG (can include transparency) or JPG file that represents this skill. Displays in the Alexa App.
- Large Icon
-- 512 x 512 pixel PNG (can include transparency) or JPG file that represents this skill. Displays in the Alexa App on larger screens.

**Comment by gojirra55** [comment]
What should we title the app?

**Comment by gojirra55** [comment]
Adventure System or something that implies that we can create adventures with it.
